Repository Meet-Coder-Study/posting-review, pull requests merged in 2021-11, with the labels that each got.

#865 [박경철] Redis PubSub
  pkch93/2021-10-28-redis-pubsub.md
Labels: 2주차, 6기

#863 [권시연] Hosting의 개념
  SiyeonKwon/2021-10-28-hosting.md
  SiyeonKwon/images/web_hosting.png
Labels: 2주차, 6기

#867 [김민걸] interceptor
  kimmingeor/2021-10-30-interceptor.md
  kimmingeor/img/interceptor.png
Labels: 2주차, 6기

#866 [김광훈] Introduction caffeine cache
  kwanghoon/2021-10-30-Introduction-caffeine-cache.md
  kwanghoon/image/Clustered Cache.png
  kwanghoon/image/GlobalCache.png
  kwanghoon/image/LocalCache.png
  kwanghoon/image/intro-caffeine-docs.png
  kwanghoon/image/intro_caffeine.png
  kwanghoon/image/offheap.png
  kwanghoon/image/read&write-benchmark.png
  kwanghoon/image/read-benchmark.png
  kwanghoon/image/upbit.png
  kwanghoon/image/write-benchmark.png
Labels: 2주차, 6기

#864 [김형준] 이펙티브 코틀린 1주차 회고
  hyoungJune/2021-10-28-effectiveKotlin-1week.md
Labels: 2주차, 6기

#862 [이한결] 헤드리스 브라우저(Headless Browser)
  HangyulLee/2021-10-29-headlessbrowser.md
  HangyulLee/images/headless-screenshot.png
Labels: 2주차, 6기

#875 [김남윤] 트랜잭션 락
  yun/2021-11-06-transaction-lock.md
Labels: 3주차, 6기

#873 [김석래] RealWorld에서 3주차 생존기
  sr/realworld/_2_jacoco_n_sonarqube.md
  sr/realworld/images/_2_1.png
  sr/realworld/images/_2_2.png
  sr/realworld/images/_2_3.png
  sr/realworld/images/_2_4.png
  sr/realworld/images/_2_5.png
  sr/realworld/images/_2_6.png
Labels: 3주차, 6기

#871 [홍창섭]JPA 연관관계 매핑 기초
  changsub/-JPA- 연관관계 매핑 기초.md
Labels: 3주차, 6기

#876 Vue Enterprise Patterns — How to Build Components With Design System Variants(Vue Enterprise Patterns — 디자인 시스템 변형과 함께 컴포넌트들을 빌드하는 방법)
  SeYunKim/vue_enterprise_patterns_how_to_build_components_with_design_system_variants.md
Labels: 3주차, 6기

#874 [주현수] Gatsby 구글 웹 폰트 에서 셀프 호스트 폰트 최적화 적용기
  HyunsuJoo/2021-11-04-webFont.md
  HyunsuJoo/images/after_local_font.png
  HyunsuJoo/images/after_optimize_google_font.png
  HyunsuJoo/images/display_swap_after.png
  HyunsuJoo/images/display_swap_before.png
  HyunsuJoo/images/eot.png
  HyunsuJoo/images/font.gif
  HyunsuJoo/images/googlefont_lighthouse.png
  HyunsuJoo/images/lighthouse.png
  HyunsuJoo/images/lighthouse_optimize_before.png
  HyunsuJoo/images/nopreconnect.png
  HyunsuJoo/images/preconnect.png
  HyunsuJoo/images/preload.png
  HyunsuJoo/images/render_blocking_google_font.png
  HyunsuJoo/images/ttf.png
  HyunsuJoo/images/webfont_problem.png
  HyunsuJoo/images/woff.png
  HyunsuJoo/images/woff2.png
Labels: 3주차, 6기

#870 [김지애] Hystrix Circuit Breaker 파헤치기
  jiaekim/2021-11-02-hystrix.md
Labels: 3주차, 6기

#868 [박창원] HTTP 상태 코드
  cwpark/web/2021-11-04-HTTP-status-code.md
Labels: 3주차, 6기

#872 [구민규] React에서 side effect를 관리하는 법
  GuMinGyu/2021-11-04-react에서-side-effect를-관리하는-법.md
  GuMinGyu/image/functional-book.jpeg
  GuMinGyu/image/redux-saga.png
Labels: 3주차, 6기

#880 [김형준] 이펙티브 코틀린 2주차 회고
  hyoungJune/2021-11-11-effectiveKotlin-2week.md
Labels: 4주차, 6기

#879 [권시연] GitHub와 코드리뷰
  SiyeonKwon/2021-11-11-pull_request.md
  SiyeonKwon/images/comment.png
  SiyeonKwon/images/comment2.png
  SiyeonKwon/images/create_branch.png
  SiyeonKwon/images/create_pull_request.png
  SiyeonKwon/images/create_pull_request2.png
  SiyeonKwon/images/create_pull_request3.png
  SiyeonKwon/images/filename_error.png
  SiyeonKwon/images/filename_error2.png
  SiyeonKwon/images/fork.png
  SiyeonKwon/images/merge.png
  SiyeonKwon/images/repo_update.png
  SiyeonKwon/images/repo_update2.png
  SiyeonKwon/images/repo_update3.png
Labels: 4주차, 6기

#878 [박경철] layered architecture와 hexagonal architecture
  pkch93/2021-11-11-architectures.md
Labels: 4주차, 6기

#882 [이민호] AOP 프로그래밍 이란?
  minholee93/2021-11-13-aop-programming.md
  minholee93/images/image1.png
  minholee93/images/image2.png
  minholee93/images/image3.png
  minholee93/images/image5.png
Labels: 4주차, 6기

#877 [김민걸] kotlin과 에너테이션으로 마스킹하기
  kimmingeor/2021-11-13-masking.md
Labels: 4주차, 6기

#881 [김광훈] Spring cloud sleuth 소개
  kwanghoon/2021-11-13-Spring-cloud-sleuth.md
  kwanghoon/image/hello-sleuth.png
  kwanghoon/image/intro-sleuth.png
  kwanghoon/image/mas-trace.png
  kwanghoon/image/new-thread.png
  kwanghoon/image/trace-id.jpeg
Labels: 4주차, 6기

#883 [김남윤] Resilience4j를 이용한 서킷 브레이커 기초
  yun/2021-11-18-resilience4j-basic.md
Labels: 6주차, 6기

#887 [김세윤] Vue에서 TypeScript로 Timer의 Leading Zeros를 구현해보자.
  SeYunKim/2021-11-27-ts-landing-zero.md
Labels: 6주차, 6기

#886 [이중혁] 나는 왜 Mybatis를 어려워 할까
  LeeJungHyeok/2021-11-27-why-failed-mybatis.md
Labels: 6주차, 6기

#885 [김지애] 노션 웹클리핑
  jiaekim/2021-11-25-notion-cliping.md
Labels: 6주차, 6기

#884 [박창원] 알고리즘 시간복잡도 분석
  cwpark/algorithm/images/211125-0.png
  cwpark/algorithm/images/211125-1.png
  cwpark/algorithm/images/211125-2.png
  cwpark/algorithm/알고리즘 - 시간 복잡도 분석.md
Labels: 6주차, 6기
