Repository Meet-Coder-Study/posting-review, pull requests merged in 2021-12, with the labels that each got.

#894 [김석래] Realworld에 두 발자국 나아아기 - Architecture
  sr/realworld/_3_architecture.md
  sr/realworld/images/_3_1.png
  sr/realworld/images/_3_2.png
  sr/realworld/images/_3_3.png
  sr/realworld/images/_3_4.png
  sr/realworld/images/_3_5.png
  sr/realworld/images/_3_6.png
  sr/realworld/images/_3_7.png
Labels: 7주차, 6기

#891 [권시연] 프리코스 1주 차 참여 후기
  SiyeonKwon/2021-12-02-precourse1.md
  SiyeonKwon/images/numberBaseball.jpg
Labels: 7주차, 6기

#892 [김광훈] MySQL 8.0 InnoDB Parallel Threads for Online DDL Operations 정리 (번역)
  kwanghoon/2021-12-02_MySQL_8.0_InnoDB_Parallel_Threads.md
  kwanghoon/image/Caffeine_cache/Clustered Cache.png
  kwanghoon/image/Caffeine_cache/GlobalCache.png
  kwanghoon/image/Caffeine_cache/LocalCache.png
  kwanghoon/image/Caffeine_cache/intro-caffeine-docs.png
  kwanghoon/image/Caffeine_cache/intro_caffeine.png
  kwanghoon/image/Caffeine_cache/offheap.png
  kwanghoon/image/Caffeine_cache/read&write-benchmark.png
  kwanghoon/image/Caffeine_cache/read-benchmark.png
  kwanghoon/image/Caffeine_cache/upbit.png
  kwanghoon/image/Caffeine_cache/write-benchmark.png
  kwanghoon/image/MySQL/img.png
  kwanghoon/image/MySQL/img_1.png
  kwanghoon/image/MySQL/img_2.png
  kwanghoon/image/MySQL/img_3.png
  kwanghoon/image/MySQL/img_4.png
  kwanghoon/image/MySQL/img_5.png
  kwanghoon/image/sleuth/hello-sleuth.png
  kwanghoon/image/sleuth/intro-sleuth.png
  kwanghoon/image/sleuth/mas-trace.png
  kwanghoon/image/sleuth/new-thread.png
  kwanghoon/image/sleuth/trace-id.jpeg
Labels: 7주차, 6기

#890 [구민규] Functional Programming에서 error handling 하는 법
  GuMinGyu/2021-12-02-error-handling-with-fp.md
Labels: 7주차, 6기

#888 [홍창섭] MIPS Processor and Pipeline 1편
  changsub/MIPS Processor and Pipeline 1.md
  changsub/Screen Shot 2021-12-01 at 8.57.53 PM.png
  changsub/Screen Shot 2021-12-01 at 9.05.58 PM.png
  changsub/Screen Shot 2021-12-01 at 9.11.03 PM.png
  changsub/Screen Shot 2021-12-01 at 9.11.55 PM.png
  changsub/Screen Shot 2021-12-02 at 5.05.17 PM.png
  changsub/Screen Shot 2021-12-02 at 5.38.21 PM.png
Labels: 7주차, 6기

#889 [최락준] 자바에서 double 타입 다루기
  rockjoon/2021-12-02-java-double.md
Labels: 7주차, 6기

#895 [박창원] 알고리즘 정당성 증명
  cwpark/algorithm/알고리즘 - 알고리즘의 정당성 증명.md
Labels: 8주차, 6기

#897 [김세윤] 루비의 함수
  SeYunKim/2021-12-11-ruby-function.md
Labels: 8주차, 6기

#898 [김남윤] 인텔리제이 플러그인 String Manipulation
  yun/2021-12-11-string-manipulation.md
Labels: 8주차, 6기

#905 [김석래] 현생 살기
  sr/realworld/2021-12-16_real_life.md
  sr/realworld/images/_4_1.png
  sr/realworld/images/_4_2.png
  sr/realworld/images/_4_3.png
  sr/realworld/images/_4_4.png
  sr/realworld/images/_4_5.png
Labels: 9주차, 6기

#901 [6기] 스트림 기초
  hyeinkim/2021-12-16-stream.md
  hyeinkim/images/stream.png
Labels: 9주차, 6기

#903 [김형준] 이펙티브 코틀린 마지막 회고
  hyoungJune/2021-12-17-effectiveKotlin-4week.md
Labels: 9주차, 6기

#902 [구민규] 프론트엔드에서 테스트코드짜기
  GuMinGyu/2021-12-16-프론트엔드에서-테스트코드-짜기.md
  GuMinGyu/image/dialog.png
  GuMinGyu/image/rspec.png
  GuMinGyu/image/test-lib-trend.png
  GuMinGyu/image/test.png
Labels: 9주차, 6기

#900 [6기] AWS 주요 제품군 요약
  byungwoo/2021-12-15-aws-product.md
Labels: 9주차, 6기

#904 [김광훈] 엘라스틱서치를 알아보자.
  kwanghoon/2021-12-18-Elasticsearch.md
  kwanghoon/image/elasticsearch/component.png
  kwanghoon/image/elasticsearch/indexing.png
  kwanghoon/image/elasticsearch/index구조.png
  kwanghoon/image/elasticsearch/inverted_index.png
  kwanghoon/image/elasticsearch/inverted_index_2.png
  kwanghoon/image/elasticsearch/rdbms.png
Labels: 9주차, 6기

#913 [김남윤] 회고
  yun/2021-12-23-회고.md
Labels: 회고, 6기

#921 [6기][김민걸] 회고
  kimmingeor/2021-12-24-회고.md
Labels: 10주차, 회고, 6기

#920 [6기][박경철] 회고
  pkch93/2021-12-24-6th-retrospective.md
Labels: 10주차, 회고, 6기

#918 [6기][김지애] 회고
  jiaekim/2021-12-24-6기-회고.md
Labels: 10주차, 회고, 6기

#917 [6기][김혜인] 회고
  hyeinkim/2021-12-24-회고.md
Labels: 10주차, 회고, 6기

#916 [6기][이한결] 회고
  HangyulLee/2021-12-23-review.md
Labels: 10주차, 회고, 6기

#915 [김남윤] 회고
  yun/2021-12-23-회고.md
Labels: 10주차, 회고, 6기

#912 [6기][김석래] 회고
  sr/retrospect/2021-12-23-retrospect-6th.md
Labels: 10주차, 회고, 6기

#911 [구민규] 회고
  GuMinGyu/2021-12-23-회고.md
Labels: 10주차, 회고, 6기

#910 [6기][이중혁] 회고
  LeeJungHyeok/2021-12-23-one-year-meet-coder.md
Labels: 10주차, 회고, 6기

#909 [6기][김광훈] 회고
  kwanghoon/2021-12-23-회고.md
Labels: 10주차, 회고, 6기
