Repository Meet-Coder-Study/posting-review, pull requests merged in 2021-08, with the labels that each got.

#789 [5기][김동환]인터럽트 개념
  donghwan/os/2021-07-24-Interrupt.md
  donghwan/os/images/interrupt-cycle.png
Labels: 4주차, 5기

#783 [5기][박창원] 자바 개발자를 위한 97가지 제안
  cwpark/java/2021-07-24-97Things-for-java-programmer.md
Labels: 4주차, 5기

#793 [5기][김혜인] HLS
  git
  hyeinkim/2021-07-31-hls.md
  hyeinkim/images/Aadaptive-Bitrate-Streaming-Graphic.png
  hyeinkim/images/fmp4-hls.png
  hyeinkim/images/stream_playlists.png
  hyeinkim/images/ts-hls.png
Labels: 4주차, 5기

#785 [5기][김나은] 네트워크: 소켓, TCP/IP 개념 정리
  naeun/2021-07-28-network.md
  naeun/images/2021-07-28-network/layers.png
  naeun/images/2021-07-28-network/osi_tcpip.png
  naeun/images/2021-07-28-network/프로토콜스택.png
Labels: 4주차, 5기

#788 [5기][김지애] RabbitMQ 란?
  jiaekim/2021-07-27-rabbit-mq.md
Labels: 4주차, 5기

#786 [5기][이병우] Elasticsearch를 구성하는 기본 개념
  byungwoo/2021-07-28-elasticsearch-concepts.md
  byungwoo/images/elasticsearch-cluster.png
  byungwoo/images/elasticsearch-segment-merge.jpg
  byungwoo/images/elasticsearch-segment-work-process.jpeg
  byungwoo/images/elasticsearch-segment.png
  byungwoo/images/elasticsearch-shard.png
  byungwoo/images/split-brain.png
Labels: 4주차, 5기

#787 [5기][홍창섭] 자바스크립트에서 동기와 비동기에 대한 처리방식
  changsub/[홍창섭]JavaScript에서의 동기와 비동기 처리방식.md
Labels: 4주차, 5기

#790 [5기][강예원]RIOT API를 활용하는 discord bot 개발하기(1)
  yewon/2021-07-29-RIOT-API-DISCORD-BOT.md
Labels: 4주차, 5기

#784 [5기][이준균] spring batch jpa multi datasource, transaction 정리
  LeeJunGyun/2021-07-28-spring batch jpa multi datasource, transaction 정리.md
Labels: 4주차, 5기

#792 [5기][이중혁] Riot Data Dragon Json Data Class 파싱하기
  LeeJungHyeok/2021-07-30-riot-static-data-json.md
  LeeJungHyeok/images/rune_build.png
  LeeJungHyeok/images/rune_result.png
  LeeJungHyeok/images/runes json.png
Labels: 4주차, 5기

#794 [5기][김남윤] Config Server
  yun/2021-08-01-spring-config-server.md
Labels: 5주차, 5기

#795 [5기][김석래] 개발자가 공부하는 SQL - JOIN
  sr/db/2021-07-17-db-toc.md
  sr/db/contents/2021-07-17-db-dbms.md
  sr/db/contents/2021-07-23-db-index.md
  sr/db/contents/2021-07-24-db-mysql-architecture.md
  sr/db/contents/2021-08-07-db-join.md
  sr/db/contents/2021-08-07-db-join2.md
  sr/db/images/database.001.jpeg
  sr/db/images/database.002.jpeg
  sr/db/images/database.003.jpeg
  sr/db/images/database.004.jpeg
  sr/db/images/database.005.jpeg
  sr/db/images/database.006.jpeg
Labels: 5주차, 5기

#796 [5기][최락준] 객체를 더 스마트하게 생성하는 방법
  rockjoon/2021-08-05-smarter-way-to-create-object.md
  rockjoon/images/createInstance1.png
Labels: 5주차, 5기

#798 [5기][허원철] jar 파일 내 file 다루는 방법
  heowc/2021-08-05-handling-file-inside-jar.md
Labels: 5주차, 5기

#797 [5기][구민규] React가 Class Component에서 Functional Component로 패러다임을 전환한 이유
  GuMinGyu/2021-08-05-react-class-component-functional-component.md
Labels: 5주차, 5기

#804 [5기][김나은] 프로젝트를 진행하며 배운 내용 - 1
  naeun/2021-08-12-프로젝트를_하면서_새롭게_배운_것.md
  naeun/images/2021-08-12-프로젝트/commit_submodule.png
  naeun/images/2021-08-12-프로젝트/remote_submodule.png
Labels: 6주차, 5기

#810 [5기][이중혁] DP
  LeeJungHyeok/2021-08-13-DP.md
  LeeJungHyeok/images/fiboresult.png
  LeeJungHyeok/images/fibos.png
Labels: 6주차, 5기

#807 [5기][박경철] spring boot actuator와 헬스체크
  pkch93/2021-08-12-actuator-healthcheck.md
Labels: 6주차, 5기

#809 [5기][김지애] gradle
  jiaekim/2021-08-13-gradle.md
Labels: 6주차, 5기

#805 [5기][박창원] 디자인패턴은 어떻게 탄생하였나
  cwpark/oop/2021-08-12-Design-Patterns.md
Labels: 6주차, 5기

#802 [5기][홍창섭]스프링 컨테이너와 스프링 빈
  changsub/[홍창섭]스프링 컨테이너와 스프링 빈.md
  changsub/images/스크린샷 2021-08-10 오전 11.15.57.png
  changsub/images/스크린샷 2021-08-10 오전 11.18.32.png
  changsub/images/스크린샷 2021-08-10 오전 11.21.25.png
  changsub/images/스크린샷 2021-08-10 오전 11.32.07.png
  changsub/images/스크린샷 2021-08-10 오전 11.54.06.png
  changsub/images/스크린샷 2021-08-10 오후 3.10.58.png
  changsub/images/스크린샷 2021-08-10 오후 3.14.14.png
  changsub/images/스크린샷 2021-08-10 오후 4.10.05.png
  changsub/images/스크린샷 2021-08-10 오후 4.18.24.png
Labels: 6주차, 5기

#800 [5기][이준균] spring rest doc 정리
  LeeJunGyun/2021-08-11-spring rest doc 정리.md
Labels: 6주차, 5기

#803 [5기][홍유진] OS - 메모리관리와 가상메모리
  yujin/2021-08-12-os-memory-management-and-virtrual-memory.md
Labels: 7주차, 5기

#806 [5기][이병우] 야, 너두 오픈소스 기여할 수 있어 (feat. 야나두)
  byungwoo/2021-08-12-opensource.md
  byungwoo/images/you-can-do.jpeg
  byungwoo/img.png
  byungwoo/img_1.png
  byungwoo/img_10.png
  byungwoo/img_11.png
  byungwoo/img_12.png
  byungwoo/img_13.png
  byungwoo/img_14.png
  byungwoo/img_3.png
  byungwoo/img_4.png
  byungwoo/img_5.png
  byungwoo/img_6.png
  byungwoo/img_7.png
  byungwoo/img_8.png
  byungwoo/img_9.png
Labels: 6주차, 5기

#812 [5기][김남윤] Cloud Config & Cloud Bus 카프카를 이용한 Config 변경사항 전파
  yun/2021-08-19-config-client.md
Labels: 7주차, 5기

#813 [5기][김석래] 부분 범위 처리에 대한 쿼리
  sr/db/2021-07-17-db-toc.md
  sr/db/contents/2021-08-21-db-partial.md
Labels: 7주차, 5기

#815 [5기][구민규] HTTP Caching
  GuMinGyu/2021-08-19-http-caching.md
Labels: 7주차, 5기

#816 [5기] [홍유진] process
  yujin/2021-08-20-process.md
Labels: 7주차, 5기

#814 [5기][최락준] 파라미터 수 줄이기
  rockjoon/2021-08-19-reducing-the-number-of-parameters.md
Labels: 7주차, 5기

#801 [5기][이리나] 파이썬-GIL
  Lina Yi/2021_08_12_파이썬의 GIL.md
Labels: 7주차, 5기

#811 [5기][홍석현]NSOperationQueue 와 GCD Queue 의 차이점을 설명하시오.
  2021_01_14_프로세스와_스레드.md
  SHHong/2021-08-05-앱 화면의 콘텐츠를 표시하는 로직과 관리를 담당하는 객체를 무엇이라고 하는가?.md
  SHHong/2021-08-19-NSOperationQueue 와 GCD Queue 의 차이점을 설명하시오..md
Labels: 7주차, 5기

#826 [5기][주현수] Front End App을 위한 정적검사 vs 단위 vs 통합 vs E2E 테스트
  HyunsuJoo/2021-08-26-frontendTesting.md
  HyunsuJoo/images/testing-trophy.jpeg
Labels: 8주차, 5기

#824 [5기][김혜인] TCP와UDP
  hyeinkim/2021-08-26-TCP와 UDP.md
  hyeinkim/images/3way-handshake.PNG
  hyeinkim/images/tcp-header.jpg
Labels: 8주차, 5기

#822 [5기][박경철] AWS SAA-C02 합격 후기
  pkch93/2021-08-26-aws-saa-c02.md
Labels: 8주차, 5기

#823 [5기][이준균] spring transactional readonly 정리
  LeeJunGyun/2021-08-26-spring transactional readOnly 정리.md
Labels: 8주차, 5기

#817 [5기] HTTP 메서드와 URI 설계
  cwpark/web/2021-08-24-HTTP-Method-URI.md
  cwpark/web/images/1629418100051.png
Labels: 8주차, 5기

#818 [5기][김나은] CORS
  naeun/2021-08-25-CORS.md
Labels: 8주차, 5기

#821 [5기][홍창섭]스프링 싱글톤 컨테이너
  changsub/[홍창섭]싱글톤 컨테이너.md
  changsub/images/singleton_img1.png
  changsub/images/singleton_img2.png
  changsub/images/singleton_img3.png
  changsub/images/singleton_img4.png
  changsub/images/singleton_img5.png
  changsub/images/singleton_img6.png
  changsub/images/singleton_img7.png
  changsub/스크린샷 2021-08-11 오후 12.47.57.png
  changsub/스크린샷 2021-08-11 오후 5.24.54.png
  changsub/스크린샷 2021-08-11 오후 5.27.25.png
  changsub/스크린샷 2021-08-13 오후 2.44.30.png
  changsub/스크린샷 2021-08-13 오후 3.46.17.png
  changsub/스크린샷 2021-08-13 오후 7.38.33.png
  changsub/스크린샷 2021-08-13 오후 8.01.00.png
Labels: 8주차, 5기

#820 [5기][이병우] MLOps란 무엇인가 (상)
  byungwoo/2021-08-26-mlops.md
  byungwoo/images/automated-ml.png
  byungwoo/images/data-preparation.png
  byungwoo/images/devops-vs-mlops.png
  byungwoo/images/ml-lifecycle.png
  byungwoo/images/mlops-benefit.png
  byungwoo/images/model-train-tracking.png
  byungwoo/images/model-training.png
Labels: 8주차, 5기

#825 [5기][김동환] 자바 - volatile
  donghwan/java/2021-08-26-volatile.md
Labels: 8주차, 5기
