Repository Meet-Coder-Study/posting-review, pull requests merged in 2021-07, with the labels that each got.

#760 [김남윤] JPA는 왜 그러는 것일까?
  yun/2021-07-08-jpa-jpql.md
Labels: 1주차, 5기

#757 [이준균] spring message converter 설명
  LeeJunGyun/2021-07-08-spring message converter.md
Labels: 1주차, 5기

#759 [김지애] MongoDB 인덱스 설계하기
  jiaekim/2021-07-07-mongo-index.md
Labels: 1주차, 5기

#763 [김혜인] Spring HATEOAS - Pagination link 만들기
  hyeinkim/2021-07-09-spring-hateoas-pagenation.md
Labels: 1주차, 5기

#767 [이리나] 직렬과 병렬
  Lina Yi/2021-07-10_직렬과 병렬.md
Labels: 1주차, 5기

#765 [김나은] Jpa OneToMany 단방향 연관관계
  naeun/2021-07-09-jpa-mapping.md
Labels: 1주차, 5기

#766 [이중혁] Feign 설정 해보기
  LeeJungHyeok/2021-07-09-feign-apply.md
  LeeJungHyeok/images/springboot wrong feign version.png
  LeeJungHyeok/images/springboot-feign-version.png
Labels: 1주차, 5기

#761 [박창원] 쿠버네티스 백업 및 복구 오픈소스 툴 Velero 설치해보기
  cwpark/kubernetes/2021-07-08-velero.md
Labels: 1주차, 5기

#758 [박경철] AWS S3
  pkch93/2021-07-08-amazon-s3.md
Labels: 1주차, 5기

#756 [최락준] 리팩토링의 경험
  rockjoon/2021-07-08-about-refactoring.md
Labels: 1주차, 5기

#772 [김홍빈] 스타트업 신입 백엔드 개발자 6개월 생활기
  hongbin-dev/2021-07-15-retrospect_startup_backend.md
Labels: 2주차, 5기

#771 [김동환] HTTP - Keep Alive
  donghwan/network/2021-07-14-Keep_Alive.md
  donghwan/network/images/4번째_요청.png
  donghwan/network/images/5번째_요청.png
  donghwan/network/images/로그.png
Labels: 2주차, 5기

#770 [김석래] DBMS가 SQL로 데이터를 가져오는 방법
  sr/db/2021-07-17-db-toc.md
  sr/db/contents/2021-07-17-db-dbms.md
  sr/db/images/database.001.jpeg
  sr/db/images/database.002.jpeg
  sr/db/images/database.003.jpeg
  sr/db/images/database.004.jpeg
  sr/db/images/database.005.jpeg
  sr/db/images/database.006.jpeg
Labels: 2주차, 5기

#773 [5기][주현수] 브라우저 테스팅 자동화 적용기(입문) -1
  HyunsuJoo/2021-07-15-browserTesting-1.md
  HyunsuJoo/images/protocol.png
Labels: 2주차, 5기

#768 [홍창섭] 네트워크 프로토콜과 TCP/IP 모델
  changsub/[홍창섭]네트워크 프로토콜과 TCP:IP.md
  changsub/images/네트워크 프로토콜과 TCP:IP 1.png
  changsub/images/네트워크 프로토콜과 TCP:IP 2.png
  changsub/images/네트워크 프로토콜과 TCP:IP 3.png
  changsub/images/네트워크 프로토콜과 TCP:IP 4.png
Labels: 2주차, 5기

#769 [허원철] Spring WebSocket (With Stomp)
  heowc/2021-07-15-spring-websocket-with-stomp.md
Labels: 2주차, 5기

#780 [5기][허원철] ElastiCache maintenance
  heowc/2021-07-22-elasticache-maintenance.md
Labels: 3주차, 5기

#779 [5기][구민규] Data fetching library
  GuMinGyu/2021-07-22-data-fetching-library.md
Labels: 3주차, 5기

#777 [5기][김홍빈] Rails ActiveRecord와 Spring Data JPA 비교
  hongbin-dev/2021-07-15-retrospect_startup_backend copy.md
  hongbin-dev/2021-07-22-active_record.md
Labels: 3주차, 5기

#782 [5기][이리나] 프로세스와 스레드
  Lina Yi/2021-07-24-프로세스와 쓰레드.md
Labels: 3주차, 5기

#778 [5기][김남윤] Elasticsearch APM 1편
  yun/2021-07-08-jpa-jpql.md
  yun/2021-07-22-elk-apm-1.md
Labels: 3주차, 5기

#776 [5기][이승천] 주간회고 - 시퀀스 PK와 복합키 PK, DDD, 데이터중심어플리케이션 설계 등
  pnu/week2.md
Labels: 3주차, 5기

#775 [5기][홍석현] Frame과 Bounds의 차이
  SHHong/2021-07-22-Frame, Bounds.md
Labels: 3주차, 5기
