Repository Meet-Coder-Study/posting-review, pull requests merged in 2022-08, with the labels that each got.

#1063 [8기][구민규] e2e 테스트에서 api mocking 하는게 옳은가?
  GuMinGyu/2022-07-27-test-network-request.md
Labels: 7주차, 8기

#1062 [8기][김지애] 노션 API 활용
  jiaekim/2022-07-26-notion-api.md
Labels: 7주차, 8기

#1061 [8기][정재엽] 데이터베이스 트랜잭션에 대해
  Frankle/images/ACID_SingleRoom_A.png
  Frankle/images/ACID_SingleRoom_B.png
  Frankle/images/ACID_원자성.png
  Frankle/트랜잭션.md
Labels: 7주차, 8기

#1064 [8기][이건창] 임계영역
  tis/2022-07-28/임계영역.md
Labels: 7주차, 8기

#1066 [8기][김정규]야놀자 이준영님, 한기영님과 이야기하며 느낌점
  len/안전하게 코드 리팩토링하기 - 1.md
  len/야놀자 이준영님, 한기영님과 이야기하며 느낌점.md
Labels: 8주차, 8기

#1065 [8기][김석래] URL Shorter는 뭐지
  sr/design/2022-08-06_url-shoter.md
Labels: 8주차, 8기

#1067 [8기][김지애] 데일 카네기 인간관계론
  jiaekim/2022-08-10-데일카네기-인간관게론.md
Labels: 9주차, 8기

#1068 [8기][김형준] Test Double과 Stub, Mock 그리고 Fake
  hyoungJune/2022-08-10_Test Double과 Stub, Mock 그리고 Fake.md
Labels: 9주차, 8기

#1069 [8기][이건창] 스케줄링
  tis/2022-08-11/images/0.png
  tis/2022-08-11/images/1.png
  tis/2022-08-11/images/2.png
  tis/2022-08-11/운영체제 - 스케줄링.md
Labels: 9주차, 8기

#1070 [8기][강예원] NS-3 network simulator
  yewon/2022-08-13-NS3.md
Labels: 9주차, 8기

#1071 [8기][김석래] 스타일 가이드와 규칙
  sr/softskill/2022-08-20-style-guide.md
Labels: 10주차, 8기

#1072 [8기][김정규]몰라도 되는 Spring 외부화 Property 이해하기
  len/Spring PropertySource 이해하기.md
Labels: 10주차, 8기
