Repository Meet-Coder-Study/posting-review, pull requests merged in 2022-04, with the labels that each got.

#984 [7기][이병우] 쿠버네티스 파드 라이프사이클
  byungwoo/2022-03-31-pod-lifecycle.md
  byungwoo/images/pod-container-termination.png
  byungwoo/images/pod-graceful-shutdown.png
  byungwoo/images/pod-termination.png
  byungwoo/img_18.png
Labels: 7주차, 7기

#985 [7기][권시연] NFT가 붐인 이유?
  SiyeonKwon/2022-03-31_NFT.md
  SiyeonKwon/images/axie.png
  SiyeonKwon/images/nyangcat.gif
  SiyeonKwon/images/twitter.png
Labels: 7주차, 7기

#988 [7기][김형준] elasticsearch function_score(전체 데이터 스코어에 대한 글)
  hyoungJune/2022-04-01_elasticsearch function_score(전체 데이터 스코어에 대한 글)_week7.md
Labels: 7주차, 7기

#991 [7기][이건창] DBMS에서 하나의 구문을 처리 할 때 발생하는 트레이드 오프
  tis/2022-04-07/DBMS_하나의_구문에서_트레이드_오프.md
  tis/2022-04-07/images/img.png
  tis/2022-04-07/images/img_1.png
Labels: 8주차, 7기

#990 [7기][권용주]Java Serialization
  yongjukwon/2022-04-08-serializable-vs-externalizable.md
  yongjukwon/images/serialize-deserialize-java.png
Labels: 8주차, 7기

#989 [7기][김민성] 제목은 자바 오류를 찾아서 라고 하겠습니다. 근데 이제 면접 준비를 곁들인
  KimMinSeong/2022-04-07_Find_Java_Exception.md
Labels: 8주차, 7기

#993 [7기][구민규] 행복일
  GuMinGyu/2022-04-07-나는-어떻게-일하고싶은가.md
Labels: 8주차, 7기

#995 [7기][신다혜] 나답게 일한다는 것
  dahyeShin/2022-04-09-나답게일한다는것.md
Labels: 8주차, 7기

#1001 [7기] [김광훈] Describe - Context - It 테스트
  kwanghoon/2022-04-16_Describe-Context-It-pattern-test.md
Labels: 9주차, 7기

#997 [7기][박경철] Tomcat Websocket 사용시 memory leak 이슈
  pkch93/2022-04-14-websocket-tomcat.md
Labels: 9주차, 7기

#998 [7기][이병우] 쿠버네티스 구성요소
  byungwoo/2022-04-14-k8s-components.md
  byungwoo/images/etcd-raft.png
  byungwoo/images/k8s-api-server-watch.png
  byungwoo/images/k8s-api-server.png
  byungwoo/images/k8s-controller.png
  byungwoo/images/k8s-scheduling-algorithm.png
  byungwoo/images/k9s-components.png
  byungwoo/images/static-pod.png
Labels: 9주차, 7기

#1003 [7기][김혜인] #살아있다 #자프링외길12년차 #코프링2개월생존기 정리
  hyeinkim/2022-04-16-kotlin-spring.md
Labels: 9주차, 7기

#999 [7기][김석래] 개발자가 학습해야 하는 소프트웨어 아키텍처 101
  sr/study/2022-03-17-study.md
  sr/study/2022-04-16-architecture.md
Labels: 9주차, 7기

#996 [7기][권시연] 언어가 발전하는 이유
  SiyeonKwon/2022-04-14_언어가_발전하는_이유.md
Labels: 9주차, 7기

#1000 [7기][김형준] Kotest란?
  hyoungJune/2022-04-15_Kotest란?_week9.md
Labels: 9주차, 7기

#1004 [7기][이리나]클린코드_5장 - 형식맞추기
  Lina Yi/2022-03-16-정규화.md
  Lina Yi/22-04-16-클린코드_형식 맞추기.md
Labels: 9주차, 7기

#1005 [7기][김남윤] Spring Bach HTTP Page Item Reader
  yun/2022-04-17-batch-http-page-item-reader.md
Labels: 9주차, 7기

#1007 [7기][김민성] Java 18까지의 변화
  KimMinSeong/2022-04-21_Java18_Review.md
Labels: 10주차, 7기

#1008 [7기][이건창] 내가 바라본 도메인 주도 설계
  tis/2022-04-21/image/01.png
  tis/2022-04-21/내가 바라본 도메인 주도 설계.md
Labels: 10주차, 7기

#1010 [7기] [김민석] spring 으로 kakao OAuth 로그인 하기
  minseok/2022-04-20-springOAuthKakao.md
Labels: 10주차, 7기

#1006 [7기][권용주]Java Reflection
  yongjukwon/2022-04-21-reflection.md
Labels: 10주차, 7기

#1009 [7기] [최미영] spring 사용 목적과 객체지향 관계
  meeyoungchoi/2022-04-21_spring 사용 목적과 객체지향 관계.md
Labels: 10주차, 7기

#1011 [7기][김혜인] InnoDB 스토리지 엔진 구성요소 정리
  hyeinkim/2022-04-23-innodb-architecture.md
  hyeinkim/2022-04-28-7기 회고.md
  hyeinkim/images/innodb-architecture.png
  hyeinkim/images/innodb-changebuffer.png
Labels: 7기
