Repository Meet-Coder-Study/posting-review, pull requests merged in 2022-10, with the labels that each got.

#1095 [공은미] Agile 이란?
  eunmik/2022-09-29-What-is-Agile.md
  eunmik/img/563D3A44-8853-427F-B6E8-F7918B22F82D.jpeg
  eunmik/img/85A641BC-1037-472C-959C-444DF729F7E5.png
  eunmik/img/B9625EC8-DEEC-4DDA-951D-92EA89F932BE.png
  eunmik/img/C6AF9A84-A035-47E5-AA8D-F51D60896DA6.jpeg
  eunmik/img/Untitled1.png
Labels: 2주차, 9기, 백엔드

#1100 [김혜인] Redisson
  hyeinkim/2022-10-01-Redisson.md
Labels: 2주차, 9기, 백엔드

#1099 IDL 중 protobuf 잘 사용하기..!
  len/IDL 을 효과적으로 사용해보기.md
Labels: 2주차, 9기, 백엔드

#1090 [박규성] AJAX와 Axios
  프로젝트1_1.md
Labels: 2주차, 프론트, 9기

#1091 [장아연] 프론트엔드 면접 : 자바스크립트 1
  JangAyeon/2022-09-27-JS:FrontEnd-Interview.md
Labels: 2주차, 프론트, 9기

#1096 [구민규] msw
  GuMinGyu/2022-09-30-msw.md
  GuMinGyu/image/msw-diagram.jpeg
Labels: 2주차, 프론트, 9기

#1098 [김세윤] Django Performance Improvements - Part 2: Code Optimization(Django 성능 향상 - Part2: 코드 최적화)
  SeYunKim/2022-09-03-django-performance-2.md
Labels: 2주차, 9기

#1093 [박경철] 불필요한 리랜더링을 막자
  pkch93/2022-09-29-unnessesary-rerendering.md
Labels: 2주차, 프론트, 9기

#1092 [김민석] Vaadin - layout
  minseok/2022-09-29-Vaadin_layout.md
Labels: 2주차, 9기, 백엔드

#1103 [9기][김석래] 클린코드는 존재하지 않는다.
  sr/softskill/2022-10-06-clean-code.md
Labels: 3주차, 9기, 백엔드

#1110 [강한규] 어쩌다 보니... 200(or 204) vs 404 논쟁
  hangyu/2022-10-08-exception-http-api.md
  hangyu/images/2022-10-08/404-reason.png
  hangyu/images/2022-10-08/404.png
  hangyu/images/2022-10-08/4xx.png
  hangyu/images/2022-10-08/exception-handling.png
  hangyu/images/2022-10-08/java-throwable.png
  hangyu/images/2022-10-08/result.png
Labels: 3주차, 9기, 백엔드

#1112 [김남윤] 외부 인프라 스트럭처 테스트
  yun/2022-10-08-external-infrastructure-testing.md
Labels: 3주차, 9기, 백엔드

#1105 [박경철] React Context
  pkch93/2022-09-29-unnessesary-rerendering.md
  pkch93/2022-10-06-react-context-api.md
Labels: 3주차, 프론트, 9기

#1107 [정예나] swr을 통한 전역 관리
  yenowme/swr.md
Labels: 3주차, 프론트, 9기

#1106 [이태겸] AWS S3 + CloudFront로 Micro Frontend Architecture 구성하기
  taekyeom/2022-10-06-aws-s3-and-cloudfront-for-micro-frontend.md
Labels: 3주차, 프론트, 9기

#1108 [구민규] ios-safari에서 안되는 것들
  GuMinGyu/2022-10-06-ios에서-안되는것들.md
Labels: 3주차, 프론트, 9기

#1101 [박규성] 데이터통신
  guesung/데이터통신 1.md
  guesung/이미지업로드1_1.md
  guesung/프로젝트1_1.md
Labels: 3주차, 프론트, 9기

#1104 [김민석] Vaadin - Component
  minseok/2022-10-05-Vaadin_component.md
Labels: 3주차, 9기, 백엔드

#1115 [이태겸] Vite를 사용해야 하는 이유
  taekyeom/2022-10-13-why-vite.md
Labels: 4주차, 프론트, 9기

#1114 [구민규] Sentry release&deploy 잘 적용하기
  GuMinGyu/2022-10-13-sentry-잘-적용하기.md
Labels: 4주차, 프론트, 9기

#1118 [김남윤] 테스트 대역폭을 늘리기 위한 작업
  yun/2022-10-25-test-bandwidth.md
Labels: 4주차, 9기, 백엔드

#1121 서버리스 블로그 만들기
  JangAyeon/2022-09-27-JS:FrontEnd-Interview.md
  JangAyeon/2022-10-17-Serverless-DynamoDB-Flask-blog.md
  JangAyeon/image/IMG_6440.png
  JangAyeon/image/IMG_6441.png
  JangAyeon/image/IMG_6442.png
  JangAyeon/image/IMG_6443.png
  JangAyeon/image/IMG_6444.png
  JangAyeon/image/IMG_6445.png
  JangAyeon/image/IMG_6446.png
  JangAyeon/image/IMG_6447.png
  JangAyeon/image/IMG_6448.png
  JangAyeon/sample.py
Labels: 6주차, 프론트, 9기

#1122 [이태겸] 지연 로딩 (feat. 함수형 프로그래밍)
  taekyeom/2022-10-27-lazy-evaluation.md
Labels: 6주차, 프론트, 9기

#1119 컴포넌트 팁
  guesung/컴포넌트 팁.md
Labels: 6주차, 프론트, 9기

#1123 [박경철] 조금 늦은 feconf 2022 후기
  pkch93/2022-10-27-feconf2022.md
Labels: 6주차, 프론트, 9기

#1120 API 버저닝 전략
  EP/API 버저닝 전략.md
Labels: 6주차, 9기, 백엔드
