Repository Meet-Coder-Study/posting-review, pull requests merged in 2022-06, with the labels that each got.

#1012 [7기][권시연] 회고
  SiyeonKwon/2022-04-24_7기회고.md
Labels: 10주차, 회고, 7기

#1025 [7기][김남윤] 회고
  yun/2022-04-30-회고.md
Labels: 10주차, 회고, 7기

#1024 [7기][김다슬] 회고
  daseul/2022-04-29-retrospect.md
Labels: 회고, 7기

#1023 [7기][이건창] 회고
  tis/2022-04-29/마지막_회고.md
Labels: 회고, 7기

#1022 [7기][김보배] 7기 회고
  KimDoubleB/2022-04-29_7th_end.md
Labels: 10주차, 회고, 7기

#1021 [7기][김형준] 7기 회고
  hyoungJune/2022-04-29_end_week10.md
Labels: 10주차, 회고, 7기

#1020 [7기][김민석] 7기 회고
  minseok/220429_Retrospective.md
Labels: 회고, 7기

#1019 [7기][김광훈] 7기 회고
  kwanghoon/2022-04-28_회고.md
Labels: 10주차, 회고, 7기

#1018 [7기][김민성] 회고
  KimMinSeong/2022-04-28_회고.md
Labels: 10주차, 회고, 7기

#1017 [7기][이병우] 회고
  byungwoo/2022-04-28-retrospect.md
Labels: 10주차, 회고, 7기

#1016 [7기] [최미영] 회고
  meeyoungchoi/2022-04-28_10주차-회고.md
Labels: 10주차, 회고, 7기

#1015 [7기][김석래] 회고
  sr/retrospect/2022-04-30-retrospect-7th.md
Labels: 10주차, 회고, 7기

#1014 [7기][박경철] 7기 회고
  pkch93/2022-04-28-7th-retrospective.md
Labels: 10주차, 회고, 7기

#1013 [7기][권용주]회고
  yongjukwon/2022-03-24-how-flutter-renders-elements.md
  yongjukwon/2022-04-08-java-serializable-vs-externalizable.md
  yongjukwon/2022-04-21-java-reflection.md
  yongjukwon/2022-04-30-retrospective.md
Labels: 10주차, 회고, 7기

#1032 [8기][김세윤] 9 tips to Increase your Java performance(자바 성능을 향상시키기 위한 9가지 팁)
  SeYunKim/9-tips-to-increase-your-java-performance.md
Labels: 1주차, 8기

#1029 [8기][이건창] 공통적인 운영체제 구조
  tis/2022-06-16/images/0.png
  tis/2022-06-16/images/1.png
  tis/2022-06-16/images/10.png
  tis/2022-06-16/images/2.png
  tis/2022-06-16/images/3.png
  tis/2022-06-16/images/4.png
  tis/2022-06-16/images/5.png
  tis/2022-06-16/images/6.png
  tis/2022-06-16/images/7.png
  tis/2022-06-16/images/8.png
  tis/2022-06-16/images/9.png
  tis/2022-06-16/운영체제의-공통적인-구조.md
Labels: 1주차, 8기

#1031 [8기][강예원] RDMA
  yewon/2022-06-16-RDMA.md
Labels: 1주차, 8기

#1033 [8기][구민규] 직교성
  GuMinGyu/2022-06-17-직교성.md
Labels: 1주차, 8기

#1027 [8기][김지애] Kafka란?
  jiaekim/2022-06-15-kafka.md
Labels: 1주차, 8기

#1026 [8기][김형준]리스트에 대한 방어적 복사와 읽기전용
  hyoungJune/2022-06-15-리스트에 대한 방어적 복사와 읽기전용-8기-1week.md
Labels: 1주차, 8기

#1030 [8기][홍창섭]알고쓰는 즉시로딩과 지연로딩
  changsub/8기/Screen Shot 2022-04-30 at 3.00.57 PM.png
  changsub/8기/Screen Shot 2022-04-30 at 3.05.41 PM.png
  changsub/8기/Screen Shot 2022-04-30 at 3.20.36 PM.png
  changsub/8기/즉시로딩과 지연로딩.md
Labels: 1주차, 8기

#1028 [8기][김남윤] Sleuth 분산 환경 트래킹 With Fuel
  yun/2022-06-16-slueth-fuel.md
Labels: 1주차, 8기

#1038 [8기][김정규] 이벤트소싱(?)이벤트스토어(?) 활용하면서 느낀점
  len/이벤트 스토어(?) 이벤트 소싱(?) 를 활용한 View 를 반복적으로 만들고 부수면서 느낀 점.md
Labels: 2주차, 8기
