Repository Meet-Coder-Study/posting-review, pull requests merged in 2023-11, with the labels that each got.

#1242 [김동인] 지수 백오프(Exponential backoff) 재시도 전략
  EP/지수 백오프(Exponential backoff) 재시도 전략.md
Labels: 1주차, 11기

#1247 [구민규] payment 이야기
  GuMinGyu/2023-11-03-payment.md
  GuMinGyu/image/pg.png
  GuMinGyu/image/van.png
Labels: 1주차, 11기

#1248 [김세윤] Java String의 isEmpty와 isBlank
  SeYunKim/isEmpty-vs-isBlank
Labels: 1주차, 11기

#1246 [신은지] AOP와 Spring AOP를 뜯어보자 (feat. Proxy, @Transactional)
  EunjiShin/2023-11-04-AOP-and-Spring-AOP.md
Labels: 1주차, 11기

#1238 [이병우] FinOps 맛보기
  byungwoo/2023-11-02-finops.md
  byungwoo/img_17.png
Labels: 1주차, 11기

#1240 [이종현]boto3를 활용한 AWS Service Quota 모든 증설이력 확인하기
  jonghyun/2023-11-03-ServiceQuota-Comparison.md
Labels: 1주차, 11기

#1244 [이건창] 잘하고 있는지 걱정 되서 한 정리
  tis/2023-11-03/gomin.md
Labels: 1주차, 11기

#1243 [김형준] feature-toggle이란?
  hyoungJune/2023-11-03-feature-toggle이란?.md
Labels: 1주차, 11기

#1236 [김학진] [requests 라이브러리] 내가 아는 timeout은 너무 추상적이였어..
  mildsalmon/2023-10-28-[requests 라이브러리] 내가 아는 timeout은 너무 추상적이였어.md
Labels: 1주차, 11기

#1251 [김형준] 도메인 주도 설계 첫걸음 정리. Part1 전략적 설계
  hyoungJune/2023-11-06-도메인 주도 설계 첫걸음-Part1 전략적 설계.md
Labels: 2주차, 11기

#1250 [김학진] [Spark 맛보기 - 3] transformation, action, lazy evaluation
  mildsalmon/2023-11-05-[Spark 맛보기 - 3] transformation, action, lazy evaluation.md
  mildsalmon/images/1_action.png
Labels: 2주차, 11기

#1249 [김혜인] OpenCSV를 사용해서 CSV 파일 읽기
  hyeinkim/2023-11-04-OpenCSV를 사용해서 파일 읽기.md
  hyeinkim/images/flow.png
Labels: 1주차, 11기

#1241 [김경훈] Key-Value DB 설계하기
  kyunghun/2023-11-03-key-value-nonsqlDB-architecture.md
  kyunghun/image/const_hashing.png
  kyunghun/image/merkle_tree.png
Labels: 1주차, 11기

#1239 [배진오] 이번 SPA 개발은 앵귤러 어떠세요?
  JinoBae/2023-11-03-create-spa-with-angular.md
Labels: 1주차, 11기

#1234 [김남윤] JPA 페이징 Performance 향상 방법
  yun/2023-10-28-page-query-performance.md
Labels: 1주차, 11기

#1271 [김혜인] FTP
  hyeinkim/2023-11-11-ftp.md
  hyeinkim/images/ftp-active-mode.png
  hyeinkim/images/ftp-passive-mode.png
Labels: 2주차, 11기

#1257 [김남윤] Spring Data MongoDB Repository 확장
  yun/2023-11-06-mongo-repository.md
Labels: 2주차, 11기

#1268 [김경훈] dto에서의 setter사용
  kyunghun/2023-11-11-setter-usage-of-dto.md
  kyunghun/image/const_hashing.png
  kyunghun/image/merkle_tree.png
Labels: 2주차, 11기

#1266 [한승원] 동시성 테스트 및 문제 해결 방법
  seungwon/2023-11-10-concurrency-issue.md
Labels: 2주차, 11기

#1264 [김범석] No thread-bound request found 예외 발생 이유와 해결법
  BeomSeog/2023-11-10-No-thread-bound-request-found.md
Labels: 2주차, 11기

#1263 [AWS] CloudWatch agent를 통한 Group 레벨 메모리 메트릭 관찰하기
  jonghyun/2023-11-10-Get_GroupLevel_Memory_Metric_via_CloudwatchAgent.md
Labels: 2주차, 11기

#1269 [이병우] ITGC 소개
  byungwoo/2023-11-09-itgc.md
  byungwoo/img_19.png
Labels: 2주차, 11기

#1258 [김학진] [Spark 맛보기 - 3] transformation, action, lazy evaluation
  mildsalmon/2023-11-05-[Spark 맛보기 - 3] transformation, action, lazy evaluation.md
  mildsalmon/images/1_action.png
Labels: 2주차, 11기

#1256 [안주형] [Docker-MySQL] Orchestrator를 이용한 High Availability(HA) 구축하기
  juhyeong/2023-11-06-[Docker MySQL] Orchestrator를 이용한 High Availability(HA) 구축하기.md
Labels: 2주차, 11기

#1259 [김세윤] Java의 toList()에 대한 고찰
  SeYunKim/java-toList.md
Labels: 2주차, 11기

#1261 [배진오] 소소한 타입스크립트 팁
  JinoBae/2023-11-10-typescript-small-tips.md
Labels: 2주차, 11기

#1262 [신은지] 클래스 응집도의 중요성, 그리고 완전 생성자와 값 객체
  EunjiShin/2023-11-10-class-cohension-and-etc.md
Labels: 2주차, 11기

#1270 [구민규] 아주 작은 습관의 힘
  GuMinGyu/2023-11-11-folder.md
Labels: 2주차, 11기

#1283 [김세윤] jest 27 -> 28 자충우돌 upgrade
  SeYunKim/jest27-jest28-upgrade.md
Labels: 3주차, 11기

#1280 [이종현] ECS Capacity Provider - Deep Dive (1).md
  jonghyun/2023-11-18-ECS Capacity Provider - Deep Dive(1).md
Labels: 3주차, 11기

#1272 [안주형] [Docker-MySQL] Proxy Layer 구축하기
  juhyeong/2023-11-13-[Docker MySQL] Proxy Layer 구축하기.md
Labels: 3주차, 11기

#1274 [한승원] Jmeter(부하테스트 도구)로 테스트 시나리오 작성
  seungwon/2023-11-16-jmeter-scenario-test.md
Labels: 3주차, 11기

#1281 [신은지] 일급 컬렉션에 대하여
  EunjiShin/2023-11-17-first-class-collection.md
Labels: 3주차, 11기

#1276 [김학진] Spark 맛보기 - 4. RDD, DataFrame, DataSet API
  mildsalmon/2023-11-17-[Spark 맛보기 - 4] RDD, DataFrame, DataSet API.md
  mildsalmon/images/3_1.png
  mildsalmon/images/3_2.png
  mildsalmon/images/3_3.png
  mildsalmon/images/3_4.png
  mildsalmon/images/3_5.png
  mildsalmon/images/3_6.png
  mildsalmon/images/3_7.png
  mildsalmon/images/3_8.png
Labels: 3주차, 11기

#1279 [김경훈] 스프링 이벤트 적용기
  kyunghun/2023-11-18-eventhandler-in-spring.md
Labels: 3주차, 11기

#1282 [이건창] HTTP 헤더를 활용해 캐시 데이터를 관리하는 일
  tis/2023-11-17/cache.md
Labels: 3주차, 11기

#1275 [이병우] 내가 45년 동안 소프트웨어 업계에서 배운 점 (번역)
  byungwoo/2023-11-16-what-ive-learned-in-45-years-in-the-software-industry.md
Labels: 3주차, 11기

#1278 [김형준] 도메인 주도 설계 첫걸음-이벤트
  hyoungJune/2023-11-17-도메인 주도 설계 첫걸음-이벤트.md
Labels: 3주차, 11기

#1273 [김남윤 ]MongoDB 다양한 테스트 케이스를 커버할 수 있는 테스트 데이터 셋업 방법
  yun/2023-11-16-mongo-test-data-setup.md
Labels: 3주차, 11기

#1284 [이병우][번역] 용량 산정 (Capacity Planning)
  byungwoo/2023-11-23-capacity-planning.md
  byungwoo/img_20.png
Labels: 3주차, 11기

#1295 [김남윤] MSA 환경에 효율적인 HTTP Client 설계 방법
  yun/2023-11-25-http-client-design.md
Labels: 4주차, 11기

#1296 [김세윤] ruby의 !(Exclamation mark / Bang)의 의미
  ruby-band.md
Labels: 4주차, 11기

#1294 [김혜인] Spring Retry
  hyeinkim/2023-11-25-spring-retry.md
Labels: 4주차, 11기

#1293 [이건창] vaadin 나만 쓸 수 없다.
  tis/2023-11-25/1.png
  tis/2023-11-25/2.png
  tis/2023-11-25/vaadin-good.md
Labels: 4주차, 11기

#1291 [김학진] time travel이 가능한 DB의 원리에 대해 알아보자
  mildsalmon/2023-11-25-[Diving Into Delta Lake] time travel이 가능한 DB의 원리에 대해 알아보자.md
  mildsalmon/images/img.png
  mildsalmon/images/img_1.png
  mildsalmon/images/img_2.png
  mildsalmon/images/img_3.png
  mildsalmon/images/img_4.png
Labels: 4주차, 11기

#1290 [이종현] ECS Capacity Provider - (2).md
  jonghyun/[이종현] ECS Capacity Provider - (2).md
Labels: 4주차, 11기

#1289 [안주형] 다중 인스턴스 환경에서 단일 스케줄러 동작 보장하기 - Spring
  juhyeong/2023-11-24-[Spring] 다중 인스턴스 환경에서 단일 스케줄러 동작 보장하기.md
Labels: 4주차, 11기

#1288 [신은지] 자바의 참조 타입에서 동등성 판단하기
  EunjiShin/2023-11-24-java-reference-type-comparison.md
Labels: 4주차, 11기

#1286 [이세희] Spring Security와 HTTPS
  SeheeLee01/2023-11-10-spring-https.md
Labels: 4주차, 11기

#1292 [배진오] Angular :: Pipe
  JinoBae/2023-11-17-angular-standalone-component.md
  JinoBae/2023-11-25-angular-pipe.md
Labels: 4주차, 11기

#1285 [김형준] 도메인 주도 설계 첫걸음- 실무에서의 도메인 주도 설계
  hyoungJune/2023-11-24-도메인 주도 설계 첫걸음- 실무에서의 도메인 주도 설계.md
Labels: 4주차, 11기
