Repository Meet-Coder-Study/posting-review, pull requests merged in 2023-06, with the labels that each got.

#1169 [이건창] 옵시디언 활용 방법
  tis/2023-05-31/옵시디언활용법.md
Labels: 2주차, 10기

#1174 [김세윤] 테스트 FIRST 원칙
  SeYunKim/first.md
Labels: 2주차, 10기

#1173 [김진하] 뒤집은 소수
  jean202/2023-05-31-뒤집은소수.md
Labels: 2주차, 10기

#1172 [이하정] 네트워크 기초
  leehajeong/week2/네트워크 기초.md
Labels: 2주차, 10기

#1160 [김석래] 이펙티브 소프트웨어 테스팅 책 읽고..(2)
  sr/test/20230531-effective-software-test-2.md
Labels: 2주차, 10기

#1159 [김동인] 동시성 이슈의 사례와 트랜잭션 격리수준
  EP/동시성 이슈의 사례와 트랜잭션 격리수준.md
Labels: 2주차, 10기

#1164 [신은지] Spinlock(스핀락)에 대해 알아보자
  EunjiShin/2023-05-31-spin-lock.md
Labels: 2주차, 10기

#1167 [이종길] ECMA2023에 대해 알아보기 - 배열 메서드 중심으로
  jgjgill/2023-05-31-learn-about-ecma2023.md
Labels: 2주차, 10기

#1166 [구민규] csp, hmac 간단정리
  GuMinGyu/2023-05-31-hmac-csp.md
  GuMinGyu/image/csp-cf.png
  GuMinGyu/image/csp-report-uri-sentry.png
  GuMinGyu/image/hmac.png
Labels: 2주차, 10기

#1165 [김남윤] 인텔리제이 다양한 팁
  yun/2023-05-31-intellij-tip.md
Labels: 2주차, 10기

#1161 [박경철] Java 개발자가 배우는 Kotlin - 생성자
  pkch93/2023-05-29-kotlin-constructor.md
Labels: 2주차, 10기

#1162 [황종욱] Spring Data Common 모듈에서의 디자인 패턴
  JongWukH/2023-05-30-design-pattern-in-spring-data-common-module.md
  JongWukH/images/Untitled 1.png
  JongWukH/images/Untitled 2.png
  JongWukH/images/Untitled 3.png
  JongWukH/images/Untitled.png
  JongWukH/images/init.md
Labels: 2주차, 10기

#1163 [남혜민] IaC
  minenam/2023-05-31-IaC.md
Labels: 2주차, 10기

#1168 [이상원] 스프링 싱글톤 컨테이너
  sangwon/2023-05-31-singleton-container.md
Labels: 2주차, 10기

#1170 [이태겸] Compound Component Pattern
  taekyeom/2023-05-31-compound-component.md
Labels: 2주차, 10기

#1171 [김민철] AOP를 활용한 공통 기능 구현
  mincheolkk/AOP를 활용한 공통 기능 구현.md
Labels: 2주차, 10기

#1178 [이연우] 패키지 원칙
  ynoolee/2023-06-06-패키지원칙.md
Labels: 3주차, 10기

#1181 [김동인] Cache 알아보기
  EP/Cache 알아보기.md
Labels: 3주차, 10기

#1180 [구민규] fe 개발자가 spring boot 공부하고 느낀점
  GuMinGyu/2023-06-06-react와-spring.md
Labels: 3주차, 10기

#1176 [김석래] 이펙티브 소프트웨어 테스팅(3)
  sr/test/20230607-effective-software-test-3.md
Labels: 3주차, 10기

#1189 [김남윤] 개발을 하면서 이것 저것 정리
  yun/2023-06-07-nontile.md
Labels: 3주차, 10기

#1188 [남혜민] MySQL only_full_group_by 모드
  2023-06-07-only_full_group_by-mysql.md
Labels: 3주차, 10기

#1187 [신은지] 코틀린 쌈싸먹기
  EunjiShin/2023-06-07-kotlin-study-1.md
Labels: 3주차, 10기

#1186 [김민철] OSIV 설정 변경과 개선과정
  mincheolkk/OSIV 설정 변경과 개선과정.md
Labels: 3주차, 10기

#1185 [이종길] 참조 복사에 대해 알아보기
  jgjgill/2023-06-07-learn-about-reference-copy.md
Labels: 3주차, 10기

#1182 [박경철] Java 개발자가 배우는 Kotlin - Functional Interface
  pkch93/2023-06-05-SAM-convention.md
Labels: 3주차, 10기

#1175 [김세윤] Nuxt.js config를 통해 웹폰트를 쉽게 적용해보자.
  SeYunKim/nuxt-js-font-config.md
Labels: 3주차, 10기

#1200 [구민규] flutter 공부중...
  GuMinGyu/2023-06-14-flutter.md
Labels: 4주차, 10기

#1199 [강예원] network header
  yewon/2023-06-14-network-header.md
Labels: 4주차, 10기

#1198 [이종길] '프로그래머의 뇌'를 읽고
  jgjgill/2023-06-14-the-programmers-brain.md
Labels: 4주차, 10기

#1197 [이하정] OSI 7계층
  leehajeong/week4/OSI 7계층.md
Labels: 4주차, 10기

#1195 [남혜민] npm package.json dependencies
  minenam/2023-06-07-only_full_group_by-mysql.md
  minenam/2023-06-14-npm-package-dependencies.md
Labels: 4주차, 10기

#1192 [김남윤] 좋은 코드 설계를 위한 답없는 고민들
  yun/2023-06-11-좋은 코드 설계를 위한 답없는 고민들.md
Labels: 4주차, 10기

#1194 [박경철] Java 개발자가 배우는 Kotlin - 프로퍼티
  pkch93/2023-06-14-kotlin-properties.md
Labels: 4주차, 10기

#1193 [신은지] Jsoup으로 OG태그 메타 데이터 크롤링하기
  EunjiShin/2023-06-14-crawl-og-tag-with-jsoup.md
Labels: 4주차, 10기

#1191 [김석래] 이펙티브 소프트웨어 테스팅 책 읽고..(4)
  sr/test/20230614-effective-software-test-4.md
  sr/test/20230614-images/class-level-architecture.png
  sr/test/20230614-images/dependency-class.png
  sr/test/20230614-images/dependency-isolation-class.png
  sr/test/20230614-images/test-double-classification.png
Labels: 4주차, 10기

#1196 [이건창] 완성도가 높은 프로젝트를 구현하고 싶어!
  tis/2023-06-14/완성도가 높은 프로젝트를 구현하고 싶어.md
Labels: 4주차, 10기

#1190 [황종욱] 상품 목록 조회 시, 페이징 처리 성능 개선
  JongWukH/2023-06-11-paging-performance-improve.md
Labels: 10기

#1201 [김남윤] 실무에서 적용하는 테스트 코드 작성 방법과 노하우 Part 1: 효율적인 Mock Test
  yun/2023-06-11-좋은 코드 설계를 위한 답없는 고민들.md
  yun/2023-06-19-실무에서 적용하는 테스트 코드 작성 방법과 노하우 Part 1: 효율적인 Mock Test.md
Labels: 5주차, 10기

#1206 [이건창] 혹시 핀옵스(FinOps)를 아시나요...?
  tis/2023-06-21/핀옵스를 아시나요.md
Labels: 5주차, 10기

#1204 [김동인] Java 제네릭 타입의 공변성, 반공변성, 무변성
  EP/Java 제네릭 타입의 공변성, 반공변성, 무변성.md
Labels: 5주차, 10기

#1209 [남혜민] 쿠버네티스 이해하기 (입문)
  minenam/2023-06-21-kubernetes.md
Labels: 5주차, 10기

#1211 [신은지] Java Spring에서 처리율 제한 기능을 구현하는 4가지 방법
  EunjiShin/2023-06-21-rate-limiters-on-spring-boot-and-java.md
Labels: 5주차, 10기

#1208 [황종욱] 테스트 커버리지에 대한 생각(with SLASH21 영상)
  JongWukH/2023-06-21-test-coverage.md
Labels: 5주차, 10기

#1210 [구민규] 당근페이 6개월 지났을 때 적은 회고
  GuMinGyu/2023-06-21-회고.md
Labels: 5주차, 10기

#1207 [이종길] DOM과 친해지기
  jgjgill/2023-06-21-learn-about-dom.md
Labels: 5주차, 10기

#1205 [김형준] 솔루션 퇴사 썰
  hyoungJune/2023-06-20-솔루션 퇴사 썰.md
Labels: 5주차, 10기

#1202 [김석래] 이펙티브 소프트웨어 테스팅 책 읽고..(5)
  sr/test/20230614-effective-software-test-5.md
  sr/test/20230621-images/clean_software_architecture.png
  sr/test/20230621-images/dependency_inversion_principle.png
  sr/test/20230621-images/hexagonal_architecture.png
  sr/test/20230621-images/summary.png
  sr/test/20230621-images/test_system_flow.png
Labels: 5주차, 10기

#1203 [박경철] Java 개발자가 배우는 Kotlin - 동등성 비교
  pkch93/2023-06-20-kotlin-equals.md
Labels: 5주차, 10기
