Repository Meet-Coder-Study/posting-review, pull requests merged in 2023-07, with the labels that each got.

#1222 [신은지] Auto Increment PK Id를 노출하지 않으면서 API에 활용하는 방법
  EunjiShin/2023-06-28-auto-increment-pk-hide.md
Labels: 6주차, 10기

#1220 [이연우] 인턴이 회고로 읽은 개발자 온보딩 가이드
  ynoolee/2023-06-28-온보딩_가이드를_읽고.md
Labels: 6주차, 10기

#1223 [김민철] @OneToOne 관계에서 지연로딩
  mincheolkk/@OneToOne 관계에서 지연로딩.md.
Labels: 6주차, 10기

#1221 [남혜민] 회고 방법론
  minenam/2023-06-28-회고 방법론.md
Labels: 6주차, 10기

#1216 [이종길] CSS에 타입을 입히다 (vanilla-extract)
  jgjgill/2023-06-28-css-in-ts-vanilla-extract.md
Labels: 6주차, 10기

#1215 [박경철] Java 개발자가 배우는 Kotlin - Generics
  pkch93/2023-06-27-kotlin-generics.md
Labels: 6주차, 10기

#1219 [구민규] 타이탄의 도구들
  GuMinGyu/2023-06-28-타이탄의-도구들.md
Labels: 6주차, 10기

#1218 [이상원] 파이썬 기초 - 정수, 문자열, Iterable
  sangwon/2023-06-28-python-basic.md
Labels: 6주차, 10기

#1217 [이건창] slash 23 일부 내용 정리
  tis/2023-06-28/Slash 23 컨퍼런스 중 일부.md
Labels: 6주차, 10기

#1214 [김석래] 이펙티브 소프트웨어 테스팅(6)..
  sr/test/20230626-images/maintainability.png
  sr/test/20230626-images/test-work-flow.png
  sr/test/20230628-effective-software-test-6.md
Labels: 6주차, 10기

#1213 [김남윤] nvm 으로 node version manager 으로 노드 버전 관리
  yun/2023-06-25-node-install.md
Labels: 6주차, 10기

#1227 '소프트웨어 장인'을 읽고 (part 1)
  jgjgill/2023-07-05-software-craftsmanship-part-1.md
Labels: 7주차, 10기

#1226 [구민규] 폴더링을 어떻게 해야하나?
  GuMinGyu/2023-07-05-foldering.md
Labels: 7주차, 10기

#1225 [이건창] 코루틴을 배우기전 간단한 학습
  tis/2023-07-05/코루틴을 배우기전 간단한 학습.md
Labels: 7주차, 10기

#1224 [김남윤] Kotlin 기반 경량 ORM Exposed 추가 정리 part 3
  yun/2023-06-11-좋은 코드 설계를 위한 답없는 고민들.md
  yun/2023-07-02-exposed-3.md
Labels: 7주차, 10기

#1233 [신은지] Facade pattern의 이모저모
  EunjiShin/2023-07-12-facade-pattern.md
Labels: 8주차, 10기

#1232 [구민규] framework 논의
  GuMinGyu/2023-07-12-framework-논의.md
Labels: 8주차, 10기

#1231 '소프트웨어 장인'을 읽고 (part 2)
  jgjgill/2023-07-12-software-craftsmanship-part-2.md
Labels: 8주차, 10기

#1230 [김석래] 이펙티브 소프트웨어 테스팅..(8)
  sr/test/20230712-effective-software-test-7.md
  sr/test/20230712-images/code-level-architecture.png
  sr/test/20230712-images/package_architecture.png
  sr/test/20230712-images/test_architecture.png
Labels: 8주차, 10기

#1229 [남혜민] AWS Lambda & AWS SAM
  minenam/2023-07-12-AWS-Lambda-and-AWS-SAM.md
Labels: 8주차, 10기
