Repository Meet-Coder-Study/posting-review, pull requests merged in 2024-10, with the labels that each got.

#1328 [김조은] Nmap으로 알아보는 포트 스캐닝: Host Discovery
  joeun/2024-10-01-nmap-host-discovery.md
Labels: 1주차, 13기

#1330 [김지애] 코루틴(coroutine) 이란?
  jiaekim/2024-10-01-coroutine.md
  jiaekim/2024-10-09-feign-reactive.md
Labels: 1주차, 13기

#1329 [김석래] 가상 면접 대규모 시스템 설계 기초 2 스터디 후기 1
  sr/202410/2024-10-01-system-architecture-1.md
  sr/202410/2024-10-09-system-architecture-2.md
Labels: 1주차, 13기

#1331 [김다경] 서버 구축기 - 4. Kolla-ansible 설치 시 마주한 네트워크 문제
  S0okJu/2024-10-01-openstack-setup-and-network-problems.md
Labels: 1주차, 13기

#1336 [김예림] 세마포어 활용 사례
  yerimkim/2024-10-02-세마포어-활용-사례.md
  yerimkim/2024-10-09-네트워크-장비-IP주소-Routing.md
Labels: 1주차, 13기

#1345 [김예림] 네트워크 장비, IP주소, 라우팅
  yerimkim/2024-10-09-네트워크-장비-IP주소-Routing.md
  yerimkim/2024-10-15-CORS-정리.md
Labels: 2주차, 13기

#1343 [김다경] 왜 프로젝트를 실패했는가?
  S0okJu/2024-10-01-openstack-setup-and-network-problems copy.md
  S0okJu/2024-10-09-project-final-review.md
  S0okJu/2024-10-16-springboot-api-error-solution.md
Labels: 2주차, 13기

#1346 [김남윤] locust API 성능 테스트 도구
  yun/2024-10-09-locust.md
  yun/2024-10-16-coroutine-flow.md
Labels: 2주차, 13기

#1340 [이병우] 유효 절감률 2부: 기존 클라우드 비용 최적화 지표의 눈속임
  byungwoo/2024-10-02-effective-savings-rate-1.md
  byungwoo/2024-10-09-effective-savings-rate-2.md
  byungwoo/img_27.png
  byungwoo/img_28.png
  byungwoo/img_29.png
  byungwoo/img_30.png
Labels: 2주차, 13기

#1349 [김다경] API 개발 시 마주한 문제들
  S0okJu/2024-10-16-springboot-api-error-solution.md
Labels: 3주차, 13기

#1351 [김남윤] 코루틴 Flow을 통한 성능 개선
  yun/2024-10-16-coroutine-flow.md
Labels: 3주차, 13기

#1348 [박두원] MySQL DB 다중화
  doooo/mysql-db.md
Labels: 3주차, 13기

#1347 [김예림] CORS 정리
  yerimkim/2024-10-15-CORS-정리.md
Labels: 3주차, 13기

#1337 [안형수] Java GC 동작원리
  [안형수] Java GC의 동작원리
Labels: 2주차, 13기

#1338 [김지애] feign-reactive.md
  jiaekim/2024-10-09-feign-reactive.md
Labels: 2주차, 13기

#1341 [김석래] 가상 면접 대규모 시스템 설계 기초 2 - 예약 시스템이라는 주제에서 고민해야 할 것들
  sr/202410/2024-10-09-system-architecture-2.md
Labels: 2주차, 13기

#1342 [김조은] Nmap으로 알아보는 포트 스캐닝: Service and Application Version Detection
  joeun/2024-10-09-nmap-version-detection.md
Labels: 2주차, 13기

#1344 [최락준] 실시간 대시보드 구현(sse vs 웹소켓) 1편
  rockjoon/2024-10-09-realtime-dashboard-1/2024-10-09-realtime-dashboard-1.md
  rockjoon/2024-10-09-realtime-dashboard-1/images/1.png
  rockjoon/2024-10-09-realtime-dashboard-1/images/2.png
Labels: 2주차, 13기
